### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by marscout** [Willpmor/App#5]
Vamos criar, a primeiro momento, uma aplicação para o controle de recursos como aguá, energia elétrica, gás, etc, Utilizaremos as tecnologias Node.js, React e talvez React Native.

**Comment by Willpmor** [comment]
Correto.

Vamos focar em fazer a aplicação com as melhores metodologias possíveis, podendo usar esse conhecimento para o nosso Trabalho de Conclusão de Curso.

Obrigado pelo empenho !
